#!/usr/bin/perl
##################################
# Ahmed AlJehairan
# ahmed.jehairan@utexas.edu
# GitHub: https://github.com/aj326
##################################
# Project: Autostart redshift
# Description: 
#######################
use v5.10;
use Data::Dumper;	
use autodie;
use strict;
use warnings;
#######################
#Variables:
###########
# my @stack;
#######################
#Subroutines:
#############

#######################
#I/O
####
system ("redshift &");